defaultRules:
  rules:
    alertmanager: false

## Using default values from https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
##
grafana:
  adminPassword: prom-operator

  ## Passed to grafana subchart and used by servicemonitor below
  ##
  service:
    type: NodePort
    nodePort: 31000

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: false
        options:
          path: /var/lib/grafana/dashboards/default
  dashboards:
    default:
      argocd:
        url: https://raw.githubusercontent.com/argoproj/argo-cd/master/examples/dashboard.json

## Deploy a Prometheus instance
##
prometheus:
  service:
    nodePort: 30090
    type: NodePort

alertmanager:
  enabled: false
